name: Deploy Jekyll to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Setup Ruby environment
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'  # You can change this to the Ruby version used by your Jekyll site

      # Install dependencies
      - name: Install dependencies
        run: |
          gem install jekyll bundler
          bundle install

      # Build the Jekyll site
      - name: Build the site with Jekyll
        run: |
          bundle exec jekyll build

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # The branch to deploy to
          folder: _site     # The folder where Jekyll builds the site
