name: Backend Smoke Test
on: [push, pull_request]

jobs:
  smoke-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./api

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Start Backend and Run Smoke Test
        run: |
          nohup npm start > server.log 2>&1 &
          echo "Started backend server"
          sleep 10  # Wait for server to boot
          echo "Checking health endpoint"
          curl -v http://localhost:4000/api/health
          curl -s http://localhost:4000/api/health | grep -q '"status":"healthy"'
