name: Backend Smoke Test
on: [push, pull_request]

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api  # Set once for all steps

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci  # Now runs in ./api automatically

      - name: Create .env file
        run: |
          echo "MONGO_URI=${{ secrets.MONGO_ATLAS_URI_TEST }}" > .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET_TEST }}" >> .env
          echo "PORT=4000" >> .env

      - name: Run smoke test
        run: |
          npm start &
          SERVER_PID=$!
          sleep 10
          curl -s http://localhost:4000/api/health | grep -q '"status":"healthy"' || exit 1
          kill $SERVER_PID