name: Backend Smoke Test
on: [push, pull_request]

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      # EXPLICITLY CHANGE DIRECTORY FIRST
      - name: Navigate to api folder
        run: cd api && pwd  # Verify we're in the right place

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      # ALL FOLLOWING STEPS RUN IN /api
      - name: Verify package.json exists
        run: ls -la && cat package.json  # Debug file location
        working-directory: ./api

      - name: Install dependencies
        run: npm ci
        working-directory: ./api

      - name: Run smoke test
        working-directory: ./api
        run: |
          npm start &
          SERVER_PID=$!
          sleep 10
          curl -v http://localhost:4000/api/health  # Add verbose logging
          curl -s http://localhost:4000/api/health | grep -q '"status":"healthy"' || exit 1
          kill $SERVER_PID