name: Backend Smoke Test
on: [push, pull_request]

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    timeout-minutes: 5  # Prevent hanging jobs
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        working-directory: ./api
        run: npm ci

      - name: Create .env file
        working-directory: ./api
        run: |
          echo "MONGO_URI=${{ secrets.MONGO_ATLAS_URI_TEST }}" > .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET_TEST }}" >> .env
          echo "CLIENT_URL=${{ secrets.CLIENT_URL_TEST }}" >> .env
          echo "PORT=4000" >> .env
          echo "NODE_ENV=test" >> .env

      - name: Run smoke test
        working-directory: ./api
        run: |
          # Start server with logging
          npm start > server.log 2>&1 &
          SERVER_PID=$!
          
          # Wait for server to start (with health checks)
          for i in {1..10}; do
            if curl -s http://localhost:4000/api/health | grep -q '"status":"healthy"'; then
              echo "Server is healthy"
              break
            fi
            sleep 1
          done
          
          # Verify health check
          curl -s http://localhost:4000/api/health | grep -q '"status":"healthy"' || {
            echo "Health check failed"
            cat server.log
            exit 1
          }
          
          # Clean up
          kill $SERVER_PID || true
          wait $SERVER_PID 2>/dev/null || true